language: java
jdk:
- oraclejdk8
services:
  - mysql
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
  - mysql -e 'CREATE DATABASE test;'
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
